name: WB Pipeline

on:
  push:
    branches:
      [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Weather Module
        run: |
          cd weather  
          ./gradlew clean build 

      - name: Publish Weather Module to Maven Local
        run: |
          cd weather 
          ./gradlew publishToMavenLocal 

      - name: Build and Test
        run: ./gradlew build test

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Lint code
        run: ./gradlew lint
