name: WB Pipeline

on:
  push:
    branches:
      [ master]
    paths:
      - '**' # Watch for changes in all files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Check if README file was modified
        id: readme-check
        run: |
          git fetch origin master
          CHANGED_FILES=$(git diff --name-only origin/master)
          if echo "$CHANGED_FILES" | grep -q 'README.md'; then
            echo "::set-output name=modified::true"
          else
            echo "::set-output name=modified::false"
          fi

      - name: Skip workflow if README was the only file modified
        if: steps.readme-check.outputs.modified == 'false'
        run: exit 78 # Skip the rest of the workflow

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Weather Module
        run: |
          cd weather  
          gradle clean build 

      - name: Publish Weather Module to Maven Local
        run: |
          cd weather 
          gradle publishToMavenLocal 

      - name: Build and Test
        run: ./gradlew build test

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Lint code
        run: ./gradlew lint
